Resources:
    NotificationTable:
        Type: 'AWS::DynamoDB::Table'
        DeletionPolicy: Delete
        Properties:
            TableName: '${self:service}-${self:provider.stage}-notification-table'
            BillingMode: PAY_PER_REQUEST
            AttributeDefinitions:
                - AttributeName: id
                  AttributeType: S
                - AttributeName: targetId
                  AttributeType: S
                - AttributeName: userId
                  AttributeType: S
                - AttributeName: status
                  AttributeType: S
            KeySchema:
                - AttributeName: id
                  KeyType: HASH
            GlobalSecondaryIndexes:
                - IndexName: targetIdGlobalIndex
                  KeySchema:
                      - AttributeName: targetId
                        KeyType: HASH
                      - AttributeName: status
                        KeyType: RANGE
                  Projection:
                      ProjectionType: ALL
                - IndexName: userIdGlobalIndex
                  KeySchema:
                      - AttributeName: userId
                        KeyType: HASH
                      - AttributeName: status
                        KeyType: RANGE
                  Projection:
                      ProjectionType: ALL
    UserTable:
        Type: 'AWS::DynamoDB::Table'
        DeletionPolicy: Delete
        Properties:
            TableName: '${self:service}-${self:provider.stage}-user-table'
            BillingMode: PAY_PER_REQUEST
            AttributeDefinitions:
                - AttributeName: username
                  AttributeType: S
            KeySchema:
                - AttributeName: username
                  KeyType: HASH
    ImageTable:
        Type: 'AWS::DynamoDB::Table'
        DeletionPolicy: Delete
        Properties:
            TableName: '${self:service}-${self:provider.stage}-image-table'
            BillingMode: PAY_PER_REQUEST
            AttributeDefinitions:
                - AttributeName: id
                  AttributeType: S
            KeySchema:
                - AttributeName: id
                  KeyType: HASH
    TagTable:
        Type: 'AWS::DynamoDB::Table'
        DeletionPolicy: Delete
        Properties:
            TableName: '${self:service}-${self:provider.stage}-tag-table'
            BillingMode: PAY_PER_REQUEST
            AttributeDefinitions:
                - AttributeName: id
                  AttributeType: S
            KeySchema:
                - AttributeName: id
                  KeyType: HASH
    TagImageTable:
        Type: 'AWS::DynamoDB::Table'
        DeletionPolicy: Delete
        Properties:
            TableName: '${self:service}-${self:provider.stage}-tagImage-table'
            BillingMode: PAY_PER_REQUEST
            AttributeDefinitions:
                - AttributeName: id
                  AttributeType: S
                - AttributeName: tag
                  AttributeType: S
            KeySchema:
                - AttributeName: id
                  KeyType: HASH
            GlobalSecondaryIndexes:
                - IndexName: tagIndex
                  KeySchema:
                      - AttributeName: tag
                        KeyType: HASH
                  Projection:
                      ProjectionType: ALL
